// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aFHTma5a2mQLN8unP5zrW8
// Component: 1DTknJ06MB
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_plasmic_project.module.css"; // plasmic-import: aFHTma5a2mQLN8unP5zrW8/projectcss
import * as sty from "./PlasmicMySlider.module.css"; // plasmic-import: 1DTknJ06MB/css

export type PlasmicMySlider__VariantMembers = {};

export type PlasmicMySlider__VariantsArgs = {};
type VariantPropType = keyof PlasmicMySlider__VariantsArgs;
export const PlasmicMySlider__VariantProps = new Array<VariantPropType>();

export type PlasmicMySlider__ArgsType = {
  name?: string;
};

type ArgPropType = keyof PlasmicMySlider__ArgsType;
export const PlasmicMySlider__ArgProps = new Array<ArgPropType>("name");

export type PlasmicMySlider__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultMySliderProps {
  name?: string;
  className?: string;
}

function PlasmicMySlider__RenderFunc(props: {
  variants: PlasmicMySlider__VariantsArgs;
  args: PlasmicMySlider__ArgsType;
  overrides: PlasmicMySlider__OverridesType;
  dataFetches?: PlasmicMySlider__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMySlider__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMySlider__VariantsArgs;
    args?: PlasmicMySlider__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicMySlider__Fetches;
  } & Omit<PlasmicMySlider__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMySlider__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMySlider__ArgProps,
      internalVariantPropNames: PlasmicMySlider__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicMySlider__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMySlider";
  } else {
    func.displayName = `PlasmicMySlider.${nodeName}`;
  }
  return func;
}

export const PlasmicMySlider = Object.assign(
  // Top-level PlasmicMySlider renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicMySlider
    internalVariantProps: PlasmicMySlider__VariantProps,
    internalArgProps: PlasmicMySlider__ArgProps
  }
);

export default PlasmicMySlider;
/* prettier-ignore-end */
