// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aFHTma5a2mQLN8unP5zrW8
// Component: O4yp26B4kR
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_plasmic_project.module.css"; // plasmic-import: aFHTma5a2mQLN8unP5zrW8/projectcss
import * as sty from "./PlasmicMyButton.module.css"; // plasmic-import: O4yp26B4kR/css

export type PlasmicMyButton__VariantMembers = {};

export type PlasmicMyButton__VariantsArgs = {};
type VariantPropType = keyof PlasmicMyButton__VariantsArgs;
export const PlasmicMyButton__VariantProps = new Array<VariantPropType>();

export type PlasmicMyButton__ArgsType = {
  name?: string;
  type?: string;
};

type ArgPropType = keyof PlasmicMyButton__ArgsType;
export const PlasmicMyButton__ArgProps = new Array<ArgPropType>("name", "type");

export type PlasmicMyButton__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultMyButtonProps {
  name?: string;
  type?: string;
  className?: string;
}

function PlasmicMyButton__RenderFunc(props: {
  variants: PlasmicMyButton__VariantsArgs;
  args: PlasmicMyButton__ArgsType;
  overrides: PlasmicMyButton__OverridesType;
  dataFetches?: PlasmicMyButton__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMyButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMyButton__VariantsArgs;
    args?: PlasmicMyButton__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicMyButton__Fetches;
  } & Omit<PlasmicMyButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMyButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMyButton__ArgProps,
      internalVariantPropNames: PlasmicMyButton__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicMyButton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMyButton";
  } else {
    func.displayName = `PlasmicMyButton.${nodeName}`;
  }
  return func;
}

export const PlasmicMyButton = Object.assign(
  // Top-level PlasmicMyButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicMyButton
    internalVariantProps: PlasmicMyButton__VariantProps,
    internalArgProps: PlasmicMyButton__ArgProps
  }
);

export default PlasmicMyButton;
/* prettier-ignore-end */
